# Auto-generated by efficientnet_pipeline.ipynb
MODEL_NAME = 'skin_model'
NUM_CLASSES = 22
IMAGE_SIZE = 224
CLASS_LABELS = [
    'Acne',
    'Actinic_Keratosis',
    'Benign_tumors',
    'Bullous',
    'Candidiasis',
    'DrugEruption',
    'Eczema',
    'Infestations_Bites',
    'Lichen',
    'Lupus',
    'Moles',
    'Psoriasis',
    'Rosacea',
    'Seborrh_Keratoses',
    'SkinCancer',
    'Sun_Sunlight_Damage',
    'Tinea',
    'Unknown_Normal',
    'Vascular_Tumors',
    'Vasculitis',
    'Vitiligo',
    'Warts',
]
__all__ = ['MODEL_NAME', 'NUM_CLASSES', 'IMAGE_SIZE', 'CLASS_LABELS']
